###############################
### General training
###############################
# training
mode: 'mpnet'                  # `ae`, `mpnet`
batch_size: 512 #32              # overriden to 512 if mpnet
num_epochs: 1000
test_interval: 5 #10

lr: 0.0001
weight_decay: 0

###############################
### dataset
###############################
data_folder: 'data/data2500_tabletop/data_10sec/'
path: '_numPlansPerEnv_2500_tabletop'
ae_path: '_tabletop_idx0'   # for ae training only
lowlevel: False
thresh_plan: 2000
thresh_env: 290

sample_latent: False
###############################
### model parameters
###############################
ae_num_ptclouds: 2048
ae_latentsize: 128